/*
 * platform_user_config.h
 *
 *  Created on: 2024/9/11
 *      Author: liuzihao
 */

#ifndef PLATFORM_STM32_INCLUDE_USER_CONFIG_H
#define PLATFORM_STM32_INCLUDE_USER_CONFIG_H

#include "stm32g474xx.h"
#include "stm32g4xx_hal.h"
#include "stm32g4xx_hal_gpio.h"

//配置一些平台配置相关

#define IIC_NBR0 0
#define IIC_NBR1 1
#define STM32_I2C_INSTANCES_NBR (2U)


#define UART0_NBR0 0
#define UART0_NBR1 1
#define STM32_UART_INSTANCES_NBR (2U)


#define SPI0_NBR0 0
#define SPI0_NBR1 1
#define STM32_SPI_INSTANCES_NBR (2U)


#define STM32_NGPIO_PORTS (7)
#define STM32_GPIOA_BASE GPIOA
#define STM32_GPIOB_BASE GPIOB
#define STM32_GPIOC_BASE GPIOC
#define STM32_GPIOD_BASE GPIOD
#define STM32_GPIOE_BASE GPIOE
#define STM32_GPIOF_BASE GPIOF
#define STM32_GPIOG_BASE GPIOG

#define STM32_NGPIO_PINS (16)

#define STM32_GPIO_CHIP_BASE 0
#define STM32_GPIO_PIN(p) (STM32_GPIO_CHIP_BASE + (p))
#define STM32_USART1_TX_PIN STM32_GPIO_PIN(MOS_GPIO_PORTC | GPIO_PIN5)

#define STM32_PIN_MODE_SHIFT 0 /* Bits 0-3: mode: 0-15 */
#define STM32_PIN_MODE_MASK (15 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_INPUT (0 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_OUTPUT_PP (1 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_OUTPUT_OD (2 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_AF_PP (3 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_AF_OD (4 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_ANALOG (5 << STM32_PIN_MODE_SHIFT)

#define STM32_PIN_MODE_IT_RISING (6 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_IT_FALLING (7 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_IT_RISING_FALLING (8 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_IT_LEVEL_HIGH (9 << STM32_PIN_MODE_SHIFT)
#define STM32_PIN_MODE_IT_LEVEL_LOW (10 << STM32_PIN_MODE_SHIFT)

#define STM32_PIN_PULL_SHIFT 4 /* Bit 4-7:  Pull */
#define STM32_PIN_PULL_MASK (15 << STM32_PIN_PULL_SHIFT)
#define STM32_PIN_PULL_NOPULL (0 << STM32_PIN_PULL_SHIFT)
#define STM32_PIN_PULL_PULLUP (1 << STM32_PIN_PULL_SHIFT)
#define STM32_PIN_PULL_PULLDOWN (2 << STM32_PIN_PULL_SHIFT)

#define STM32_PIN_SPEED_SHIFT 8 /* Bit 8-11:  Speed */
#define STM32_PIN_SPEED_MASK (15 << STM32_PIN_SPEED_SHIFT)
#define STM32_PIN_SPEED_LOW (0 << STM32_PIN_SPEED_SHIFT)
#define STM32_PIN_SPEED_MEDIUM (1 << STM32_PIN_SPEED_SHIFT)
#define STM32_PIN_SPEED_HIGH (2 << STM32_PIN_SPEED_SHIFT)
#define STM32_PIN_SPEED_VERY_HIGH (3 << STM32_PIN_SPEED_SHIFT)

#define STM32_PIN_ALT_SHIFT 12 /* Bit 12-15:  Alternate */
#define STM32_PIN_ALT_MASK (15 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_0 (0 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_1 (1 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_2 (2 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_3 (3 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_4 (4 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_5 (5 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_6 (6 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_7 (7 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_8 (8 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_9 (9 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_10 (10 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_11 (11 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_12 (12 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_13 (13 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_14 (14 << STM32_PIN_ALT_SHIFT)
#define STM32_PIN_ALT_15 (15 << STM32_PIN_ALT_SHIFT)

//测试PIN
#define PLATFORM_LED2_PIN STM32_LED2_PIN
#define PLATFORM_LED2_CFG STM32_LED2_CFG
// #define STM32_LED2_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN1)
#define STM32_LED2_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN13)
#define STM32_LED2_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

//配置SPI1 PB12,PB13,PB14,PB15
#define PLATFORM_SPI1_NSS_PIN STM32_SPI1_NSS_PIN
#define PLATFORM_SPI1_NSS_CFG STM32_SPI1_NSS_CFG
#define PLATFORM_SPI1_SCK_PIN STM32_SPI1_SCK_PIN
#define PLATFORM_SPI1_SCK_CFG STM32_SPI1_SCK_CFG
#define PLATFORM_SPI1_MISO_PIN STM32_SPI1_MISO_PIN
#define PLATFORM_SPI1_MISO_CFG STM32_SPI1_MISO_CFG
#define PLATFORM_SPI1_MOSI_PIN STM32_SPI1_MOSI_PIN
#define PLATFORM_SPI1_MOSI_CFG STM32_SPI1_MOSI_CFG
#define STM32_SPI1_NSS_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN4)
#define STM32_SPI1_SCK_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN5)
#define STM32_SPI1_MISO_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN6)
#define STM32_SPI1_MOSI_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN7)
#define STM32_SPI1_NSS_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_MEDIUM | STM32_PIN_ALT_5)
#define STM32_SPI1_SCK_CFG                          \
    (STM32_PIN_MODE_AF_PP | STM32_PIN_PULL_NOPULL | \
     STM32_PIN_SPEED_VERY_HIGH | STM32_PIN_ALT_5)
#define STM32_SPI1_MISO_CFG STM32_SPI1_SCK_CFG
#define STM32_SPI1_MOSI_CFG STM32_SPI1_SCK_CFG

//配置SPI2 PB12,PB13,PB14,PB15
#define PLATFORM_SPI2_NSS_PIN STM32_SPI2_NSS_PIN
#define PLATFORM_SPI2_NSS_CFG STM32_SPI2_NSS_CFG
#define PLATFORM_SPI2_SCK_PIN STM32_SPI2_SCK_PIN
#define PLATFORM_SPI2_SCK_CFG STM32_SPI2_SCK_CFG
#define PLATFORM_SPI2_MISO_PIN STM32_SPI2_MISO_PIN
#define PLATFORM_SPI2_MISO_CFG STM32_SPI2_MISO_CFG
#define PLATFORM_SPI2_MOSI_PIN STM32_SPI2_MOSI_PIN
#define PLATFORM_SPI2_MOSI_CFG STM32_SPI2_MOSI_CFG
#define STM32_SPI2_NSS_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN12)
#define STM32_SPI2_SCK_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN13)
#define STM32_SPI2_MISO_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN14)
#define STM32_SPI2_MOSI_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN15)
#define STM32_SPI2_NSS_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_MEDIUM |STM32_PIN_ALT_5)
#define STM32_SPI2_SCK_CFG                          \
    (STM32_PIN_MODE_AF_PP | STM32_PIN_PULL_NOPULL | \
     STM32_PIN_SPEED_LOW | STM32_PIN_ALT_5)
#define STM32_SPI2_MISO_CFG STM32_SPI2_SCK_CFG
#define STM32_SPI2_MOSI_CFG STM32_SPI2_SCK_CFG

//VCC
#define PLATFORM_VCC_PIN STM32_VCC_PIN
#define PLATFORM_VCC_CFG STM32_VCC_CFG
#define STM32_VCC_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN5)
#define STM32_VCC_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

//VCC3
#define PLATFORM_VCC3_PIN STM32_VCC3_PIN
#define PLATFORM_VCC3_CFG STM32_VCC_CFG
#define STM32_VCC3_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN6)
#define STM32_VCC_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

//VCC1
#define PLATFORM_VCC1_PIN STM32_VCC1_PIN
#define PLATFORM_VCC1_CFG STM32_VCC1_CFG
#define STM32_VCC1_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN7)
#define STM32_VCC1_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

//VCC1V8
#define PLATFORM_VCC1V8_PIN STM32_VCC1V8_PIN
#define PLATFORM_VCC1V8_CFG STM32_VCC1V8_CFG
#define STM32_VCC1V8_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN7)
#define STM32_VCC1V8_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

//VCC1V2
#define PLATFORM_VCC1V2_PIN STM32_VCC1V2_PIN
#define PLATFORM_VCC1V2_CFG STM32_VCC1V2_CFG
#define STM32_VCC1V2_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN1)
#define STM32_VCC1V2_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

#define PLATFORM_COMM_UART "/dev/uart-0"
#define PLATFORM_DEBUG_UART "/dev/uart-1"

//配置串口1
#define PLATFORM_UART1_TX_PIN STM32_UART1_TX_PIN
#define PLATFORM_UART1_TX_CFG STM32_UART1_TX_CFG
#define PLATFORM_UART1_RX_PIN STM32_UART1_RX_PIN
#define PLATFORM_UART1_RX_CFG STM32_UART1_RX_CFG

#define STM32_UART1_TX_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN9)
#define STM32_UART1_RX_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN10)
#define STM32_UART1_TX_CFG                                                   \
    (STM32_PIN_MODE_AF_PP | STM32_PIN_PULL_PULLUP | STM32_PIN_SPEED_MEDIUM | \
     STM32_PIN_ALT_7)
#define STM32_UART1_RX_CFG STM32_UART1_TX_CFG

//配置串口2
#define PLATFORM_UART2_TX_PIN STM32_UART2_TX_PIN
#define PLATFORM_UART2_TX_CFG STM32_UART2_TX_CFG
#define PLATFORM_UART2_RX_PIN STM32_UART2_RX_PIN
#define PLATFORM_UART2_RX_CFG STM32_UART2_RX_CFG
#define STM32_UART2_TX_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN2)
#define STM32_UART2_RX_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN3)
#define STM32_UART2_TX_CFG                                                   \
    (STM32_PIN_MODE_AF_PP | STM32_PIN_PULL_PULLUP | STM32_PIN_SPEED_MEDIUM | \
     STM32_PIN_ALT_7)
#define STM32_UART2_RX_CFG STM32_UART2_TX_CFG

//配置IIC1
#define PLATFORM_I2C1_SCL_PIN STM32_I2C1_SCL_PIN
#define PLATFORM_I2C1_SCL_CFG STM32_I2C1_SCL_CFG
#define PLATFORM_I2C1_SDA_PIN STM32_I2C1_SDA_PIN
#define PLATFORM_I2C1_SDA_CFG STM32_I2C1_SDA_CFG

#define STM32_I2C1_SCL_PIN STM32_GPIO_PIN(MOS_GPIO_PORTA | MOS_GPIO_PIN15)
#define STM32_I2C1_SDA_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN9)
#define STM32_I2C1_SCL_CFG                          \
    (STM32_PIN_MODE_AF_OD | STM32_PIN_PULL_NOPULL | \
     STM32_PIN_SPEED_VERY_HIGH | STM32_PIN_ALT_4)
#define STM32_I2C1_SDA_CFG STM32_I2C1_SCL_CFG

// DTOF_RST
#define PLATFORM_RST_PIN STM32_RST_PIN
#define PLATFORM_RST_CFG STM32_RST_CFG
#define STM32_RST_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN11)
#define STM32_RST_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

//POWER
#define PLATFORM_DTOF_4V_EN_PIN STM32_4V_EN_PIN
#define PLATFORM_DTOF_EPC_EN_PIN STM32_EPC_EN_PIN
#define PLATFORM_DTOF_4V_EN_CFG STM32_DTOF_4V_CFG
#define PLATFORM_DTOF_EPC_EN_CFG STM32_DTOF_EPC_CFG
#define STM32_4V_EN_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN12)
#define STM32_EPC_EN_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN15)
#define STM32_DTOF_4V_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)
#define STM32_DTOF_EPC_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

// DTOF_COMMTYPE_PIN
#define PLATFORM_COMMTYPE_PIN STM32_COMMTYPE_PIN
#define PLATFORM_COMMTYPE_CFG STM32_COMMTYPE_CFG
#define STM32_COMMTYPE_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN1)
#define STM32_COMMTYPE_CFG \
    (STM32_PIN_MODE_OUTPUT_PP | STM32_PIN_PULL_NOPULL | STM32_PIN_SPEED_LOW)

// DTOF_INTERRUPT_PIN
#define PLATFORM_INTERRUPT_PIN STM32_INTERRUPT_PIN
#define PLATFORM_INTERRUPT_CFG STM32_INTERRUPT_CFG
#define STM32_INTERRUPT_PIN STM32_GPIO_PIN(MOS_GPIO_PORTB | MOS_GPIO_PIN4)

#ifdef DTOF_HM
// HM中断触发后pin拉高
#define STM32_INTERRUPT_CFG \
    (STM32_PIN_MODE_IT_RISING | STM32_PIN_PULL_PULLDOWN | STM32_PIN_SPEED_HIGH)
#else
// HML中断触发后pin拉低
#define STM32_INTERRUPT_CFG \
    (STM32_PIN_MODE_IT_FALLING | STM32_PIN_PULL_PULLUP | STM32_PIN_SPEED_HIGH)
#endif

#define IS_GPIO_PORT_VALID(__PORT__)                                \
    (((__PORT__) == 0) || ((__PORT__) == 1) || ((__PORT__) == 2) || \
     ((__PORT__) == 3) || ((__PORT__) == 4) || ((__PORT__) == 5) || \
     ((__PORT__) == 6) || ((__PORT__) == 7))

#define IS_GPIO_PIN_VALID(__PIN__)                         \
    ((((uint32_t)(__PIN__)&MOS_GPIO_PIN_MASK) != 0x00U) && \
     (((uint32_t)(__PIN__) & ~MOS_GPIO_PIN_MASK) == 0x00U))

#define IS_STM32GPIO_MODE_VALID(__MODE__)                \
    (((__MODE__) == STM32_PIN_MODE_INPUT) ||             \
     ((__MODE__) == STM32_PIN_MODE_OUTPUT_PP) ||         \
     ((__MODE__) == STM32_PIN_MODE_OUTPUT_OD) ||         \
     ((__MODE__) == STM32_PIN_MODE_AF_PP) ||             \
     ((__MODE__) == STM32_PIN_MODE_ANALOG) ||            \
     ((__MODE__) == STM32_PIN_MODE_IT_RISING) ||         \
     ((__MODE__) == STM32_PIN_MODE_IT_FALLING) ||        \
     ((__MODE__) == STM32_PIN_MODE_IT_RISING_FALLING) || \
     ((__MODE__) == STM32_PIN_MODE_IT_LEVEL_HIGH) ||     \
     ((__MODE__) == STM32_PIN_MODE_IT_LEVEL_LOW) ||      \
     ((__MODE__) == STM32_PIN_MODE_AF_OD))

#define IS_STM32GPIO_PULL_VALID(__PULL__)     \
    (((__PULL__) == STM32_PIN_PULL_NOPULL) || \
     ((__PULL__) == STM32_PIN_PULL_PULLUP) || \
     ((__PULL__) == STM32_PIN_PULL_PULLDOWN))

#define IS_STM32GPIO_SPEED_VALID(__SPEED__)     \
    (((__SPEED__) == STM32_PIN_SPEED_LOW) ||    \
     ((__SPEED__) == STM32_PIN_SPEED_MEDIUM) || \
     ((__SPEED__) == STM32_PIN_SPEED_HIGH) ||   \
     ((__SPEED__) == STM32_PIN_SPEED_VERY_HIGH))

#define DTOF_CHECK_GPIO_PARAM_RETURN(inret, outret) \
    do {                                            \
        if (!inret) return outret;                  \
    } while (0)

#define STM32_NGPIO 96 /* GPIOA-G */

#define STM32_MAXNR_IRQ (50)
#define STM32_NR_IRQS (3)
#define STM32_IRQ_EXTI4 (10)
#define STM32_IRQ_EXTI95 (23)
#define STM32_IRQ_EXTI1510 (40)

#define STM32_NR_SWINT (4)
#define STM32_IRQ_EXTI0 (6)
#define STM32_IRQ_EXTI1 (7)
#define STM32_IRQ_EXTI2 (8)
#define STM32_IRQ_EXTI3 (9)

#define PLATFORM_INT_GERATEST_PRIORITY 15

#define STM32_FLASH_BASE 0x08000000
#define STM32_FLASH_NPAGES 256
#define STM32_FLASH_PAGESIZE (2 * 1024)
#define STM32_FLASH_SIZE (STM32_FLASH_NPAGES * STM32_FLASH_PAGESIZE)

#define FLASH_LAST_PAGE_INDEX (STM32_FLASH_NPAGES - 1u)
#define STM32_LAST_PAGE_BEGIN_ADDR \
    (STM32_FLASH_BASE + (FLASH_LAST_PAGE_INDEX * STM32_FLASH_PAGESIZE))
#define STM32_LAST_PAGE_END_ADDR \
    (STM32_LAST_PAGE_BEGIN_ADDR + STM32_FLASH_PAGESIZE - 1u)
#define PAGEMAGICNUMBER 0xDEADBABEDEADF00DU


#define LED1_PORT GPIOB
#define LED1_PIN GPIO_PIN_14

#define LED2_PORT GPIOA
#define LED2_PIN GPIO_PIN_1

#define FIRMWARE_VERSION_TOF_SENSOR_NAME "one_dtof"
#define FIRMWARE_VERSION_CPU_PLATFORM_NAME "stm32"

#define SUPPORT_FUNCTIONS \
    (APP_BIT(ADAPS_FUNC_SUPPORT_SPI) | APP_BIT(ADAPS_FUNC_SUPPORT_PCTOOL))

#define ADAPS_SPI SPI1
#define ADAPS_SPI_BAUDRATEPRESCALER SPI_BAUDRATEPRESCALER_4

#ifdef TOF_RST_PORT
#undef TOF_RST_PORT
#endif

#define EGISMODULE
#ifdef EGISMODULE
#define TOF_RST_PIN GPIO_PIN_11
#define TOF_RST_PORT GPIOB
// IRQ Define
#define TOF_INTERRUPT_PORT GPIOB
#define TOF_INTERRUPT_PIN GPIO_PIN_4
#define TOF_INTERRUPT_IRQ EXTI4_IRQn
#else
#define TOF_RST_PIN GPIO_PIN_0
#define TOF_RST_PORT GPIOA
// IRQ Define
#define TOF_INTERRUPT_PORT GPIOB
#define TOF_INTERRUPT_PIN GPIO_PIN_11
#define TOF_INTERRUPT_IRQ EXTI15_10_IRQn
#endif

#ifdef DTOF_HM
#define TOF_SPI_CSB_PIN GPIO_PIN_4  // NSS
#define TOF_SPI_CSB_PORT GPIOA
#else
#define TOF_SPI_CSB_PIN GPIO_PIN_12  // NSS
#define TOF_SPI_CSB_PORT GPIOB
#endif
#define TOF_SPI_CLK_PIN GPIO_PIN_5
#define TOF_SPI_CLK_PORT GPIOA
#define TOF_SPI_DIN_PIN GPIO_PIN_6
#define TOF_SPI_DIN_PORT GPIOA
#define TOF_SPI_DOUT_PIN GPIO_PIN_7
#define TOF_SPI_DOUT_PORT GPIOA
#define TOF_4V_EN_PORT GPIOB
#define TOF_4V_EN_PIN GPIO_PIN_12
#define TOF_EPC_EN_PORT GPIOB
#define TOF_EPC_EN_PIN GPIO_PIN_15

#define TOF_TOF_COMMTYPE_PIN GPIO_PIN_1
#define TOF_TOF_COMMTYPE_PORT GPIOB

// hard ware IIC ,if not software iic
#define HARD_WARE_IIC
#define ADAPS_ADDR_W 0x82
#define ADAPS_ADDR_R 0x83
#define UART_BAUD_RATE 921600  // 921600//460800

#endif  // PLATFORM_STM32_INCLUDE_USER_CONFIG_H
