#ifndef _DTOF_VERSION_H_
#define _DTOF_VERSION_H_

#define DTOF_VERSION_MAJOR 1
#define DTOF_VERSION_MINOR 18
#define DTOF_VERSION_PATCH 0
#define DTOF_VERSION_BUILD 0

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define DTOF_VERSION_STRING STR(DTOF_VERSION_MAJOR) "." STR(DTOF_VERSION_MINOR) "." STR(DTOF_VERSION_PATCH)
#endif